import jsPDF from 'jspdf';

const generatePDF = (formData, template) => {
    // Create a new jsPDF instance
    const doc = new jsPDF({
        orientation: 'portrait', // Portrait orientation
        unit: 'mm', // Millimeters as units
        format: 'a4' // A4 size page
    });

    // Set initial position and styles
    let posY = 20;
    const fontSizeTitle = 24;
    const fontSizeSection = 16;
    const lineHeight = 10;

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(fontSizeTitle);
    doc.setTextColor(40, 84, 153); // Dark blue color
    doc.text('Job Advertisement', doc.internal.pageSize.width / 2, posY, { align: 'center' });
    posY += lineHeight * 2;

    // Company Name
    doc.setFontSize(fontSizeSection);
    doc.setFontStyle('normal');
    doc.setTextColor(0); // Black color
    doc.text(`Company Name: ${formData.companyName}`, 20, posY);
    posY += lineHeight * 1.5;

    // Job Description
    doc.text(`Job Description: ${formData.jobDescription}`, 20, posY);
    posY += lineHeight * 1.5;

    // Domain
    doc.text(`Domain: ${formData.domain}`, 20, posY);
    posY += lineHeight * 1.5;

    // Experience
    doc.text(`Experience: ${formData.experience}`, 20, posY);
    posY += lineHeight * 1.5;

    // Contact Details
    doc.text(`Contact Details: ${formData.contactDetails}`, 20, posY);
    posY += lineHeight * 1.5;

    // Template Used
    doc.setFontSize(12);
    doc.setTextColor(100); // Dark gray color
    doc.text(`Template Used: Template ${template}`, 20, posY);
    posY += lineHeight * 1.5;

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100); // Dark gray color
    doc.text('Generated by YourApp', doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: 'center' });

    // Save the PDF with a specific name
    doc.save('job-advertisement.pdf');
};

export default generatePDF;
